package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Deployment_Integration_Tests_Redemption_Account'
in the project with id = 'Tests_Integration', and delete the patch script.
*/
create(RelativeId("Tests_Integration"), BuildType({
    id("Deployment_Integration_Tests_Redemption_Account")
    name = "Redemption SOR ↭ Account SOR"

    vcs {
        showDependenciesChanges = true
    }
}))

