package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Deployment_Dev_Tests_Producers_Account'
in the project with id = 'Tests_Dev', and delete the patch script.
*/
create(RelativeId("Tests_Dev"), BuildType({
    id("Deployment_Dev_Tests_Producers_Account")
    name = "Producers :: Account SOR"

    dependencies {
        snapshot(RelativeId("Deployment_Dev_Producers_Account")) {
        }
    }
}))

