package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Tests_Dev'
in the project with id = 'Tests', and delete the patch script.
*/
create(RelativeId("Tests"), Project({
    id("Tests_Dev")
    name = "Dev"
}))

